# Generated by Django 3.1.7 on 2021-03-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=50, verbose_name='nombre')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='nombre corto')),
                ('anulate', models.BooleanField(default=False, verbose_name='anulado')),
            ],
            options={
                'verbose_name': 'mi departamento',
                'verbose_name_plural': 'Areas de la Empresa',
                'ordering': ['name'],
                'unique_together': {('name', 'short_name')},
            },
        ),
    ]
