# Generated by Django 3.1.7 on 2021-03-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades Empleados'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['-first_name', 'last_name'], 'verbose_name': 'Empleados de la Empresa'},
        ),
        migrations.AddField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('first_name', 'departamento')},
        ),
    ]
