# Generated by Django 3.1.7 on 2021-05-21 15:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
    ]
